services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
      - TYPE=FABRIC
      - VERSION=1.21.11
      - FABRIC_LOADER_VERSION=latest
      - DIFFICULTY=hard
      - MOTD=\u00A76Welcome to the \u00A7bFabric Realm\u00A7r
      - OPS=Sowevo
      - MAX_PLAYERS=5
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=100
    volumes:
      - /vol3/1000/docker-volume/minecraft/data:/data
    restart: unless-stopped
